language: node_js
node_js:
  - "lts"
dist: xenial
cache: yarn
env:
  global:
    - CC_TEST_REPORTER_ID=945dfb58a832d233a3caeb84e3e6d3be212e8c7abcb48117fce63b9adcb43647
before_script:
  - yarn lint
  - yarn lint:test
  - yarn build
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
